[project]
name = "mighty-dot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.44.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
