---
name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.5
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install dev deps (pre-commit configured in dev extras or lock)
        run: |
          uv sync --dev
          source .venv/bin/activate
          pre-commit run --all
  test:
    name: pytest (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install project (with test deps)
        run: |
          uv sync --dev
          source .venv/bin/activate
          pytest --maxfail=1 --durations=10
        env:
          PYTHONDONTWRITEBYTECODE: '1'
          PYTEST_ADDOPTS: -q
