---
name: Publish to PyPI
on:
  workflow_dispatch:
  # Trigger on published releases
  release:
    types: [published]
jobs:
  publish:
    permissions:
      # See https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.5
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install the project
        run: |
          uv sync --all-extras --dev
          pytest
      - name: Build
        run: uv build
      - name: Publish package to PyPI
        run: uv publish
